### PR TITLE
Classname support

### PR DESCRIPTION
**Pull request by jamisonprianos**
As a developer integrating the tooltip library, I would like to be able to append a specific class or classes to the rendered tooltip so that I can control styling for a single tooltip without creating extraneous wrapping elements.

### CODE REVIEW

**Comment by dennisduong** [comment]
Reasonable request. Thanks for the PR!

**Comment by jamisonprianos** [comment]
No problem. Thanks for the quick merge!

**Comment by mririgoyen** [comment]
Hi, we would find this useful. Can you please publish this version to NPM?

**Comment by dennisduong** [comment]
@goyney just published

**Comment by mririgoyen** [comment]
@dennisduong It doesn't look like the changes went in. When I install the latest version, `className` doesn't work. It looks like the dist code wasn't recompiled with the changes before the push to NPM.

**Comment by dennisduong** [comment]
@goyney I went ahead and published a new version just now. I removed "prop-types" as a dependency as it would be included with the dist files.

I double checked and className support should now be available.

**Pull request merged**
